import { launchEditedWorkflow, publishEditedWorkflow } from './launch-edited-workflow.mjs';
import { CacheCleanup } from './cache-cleanup';
import { LocalClients } from './local-clients';
import { RuntimeDependencies } from './runtime-dependencies';
import { SkillImportPanel } from './skill-import-panel';
import { WorkflowInstallPanel } from './workflow-install-panel';
import { Component, useCallback, useEffect, useState, type ReactNode } from 'react';
import { createRoot } from 'react-dom/client';
import '@xyflow/react/dist/style.css';
import './styles.css';
import { api, request, token, uid, download, InvalidContext, FormValidContext, Field, JsonField, Select, Details, Status, useLocale, type Json } from './shared';
import { Canvas, newNode, nodeKinds } from './canvas';
import { Inspector } from './inspector';
import { PackPanels } from './pack-panels';
import { RunPanel, rememberRun } from './run-panel';
import { canvasIssues } from './graph-adapter.mjs';
import { getLocale, setLocale, t as translate } from '../web/i18n.js';
import { launchWorkflowInConversation, getAppView, getInitialAppRoute, initializeAppView, isMcpAppContext, isMcpAppResource, setAppView, subscribeAppView } from './mcp-app-client';
import { confirmWorkbench } from './mcp-app-dialog';
// Keep console credentials in the fragment; URLSearchParams encodes opaque values.
function consoleHref(path: string) { return path + '#' + new URLSearchParams({ token }).toString(); }
class EditorBoundary extends Component<{ children: ReactNode, workflow: Json, edit: () => void }, { error: string | null }> {
  state: { error: string | null } = { error: null };
  static getDerivedStateFromError(error: Error) { return { error: error.message }; }
  componentDidUpdate(previous: { workflow: Json }) { if (this.state.error && previous.workflow !== this.props.workflow) this.setState({ error: null }); }
  render() { return this.state.error ? <section className="detail-page" role="alert"><h2>{translate('草稿无法绘制', 'Draft cannot be rendered')}</h2><pre>{this.state.error}</pre><p>{translate('原始 IR 已保留。修正字段后可以重新打开画布。', 'The original IR is preserved. Fix the fields, then reopen the canvas.')}</p><button onClick={this.props.edit}>{translate('打开完整 IR 修复', 'Open the full IR to repair it')}</button></section> : this.props.children; }
}
function draft(): Json {
  const final = { ...newNode('agent','final'), role: 'finalizer', name: translate('Main 验收', 'Main acceptance'), prompt_template: translate('审查上游产物和证据，明确接受后提交最终结果。', 'Review upstream artifacts and evidence, explicitly accept them, and submit the final result.') };
  return { schema_version: 1, id: uid('workflow'), name: translate('新 Workflow', 'New workflow'), description: '', enabled: true, status: 'draft', revision: 1, tags: [], inputs_schema: {}, outputs_schema: {},
    skill_policy: { mode: 'cooperative', implicit: 'deny', ambient_allow: [], shadowed_skill_paths: [] }, requirements: { providers: [], tools: [], mcp_servers: [], executables: [] }, finalization: { required: true, node_id: 'final' },
    nodes: [{ id: 'start', type: 'start', name: translate('开始', 'Start') }, final, { id: 'end', type: 'end', name: translate('结束', 'End') }], edges: [{ id: 'start-final', source: 'start', target: 'final' }, { id: 'final-end', source: 'final', target: 'end' }] };
}
function roleDraft(providers: Json[]): Json {
  const provider = providers.find(item => item.id === 'native-luna' && item.enabled && item.kind === 'native_agent' && item.capabilities?.read && item.capabilities?.write)
    ?? providers.find(item => item.enabled && item.kind === 'native_agent' && item.capabilities?.read && item.capabilities?.write);
  const role = { ...newNode('agent','role'), name: translate('角色指令', 'Role instructions'), role: 'implementer', executor: provider ? { kind: 'provider', provider_id: provider.id } : { kind: 'main' }, access: 'bounded_write', path_scope: { binding: 'run.allowed_paths' }, prompt_template: translate('根据本次任务、上下文、约束和验证要求完成工作，并返回简洁的变更与验证证据。', 'Complete the work from the task, context, constraints, and verification requirements. Return concise change and verification evidence.'), input_bindings: { task: '/inputs/task' } };
  const final = { ...newNode('agent','final'), role: 'finalizer', name: translate('Main 验收', 'Main acceptance'), executor: { kind: 'main' }, access: 'read_only', prompt_template: translate('根据任务检查角色结果与证据，然后返回验收结论。', 'Check the role result and evidence against the task, then return the acceptance result.'), input_bindings: { task: '/inputs/task', result: '/nodes/role/output' } };
  return { schema_version: 1, template_kind: 'role', role_prompt_mode: 'append_context', id: uid('role'), name: translate('新 Role', 'New role'), description: '', enabled: true, status: 'draft', revision: 1, tags: ['role'], inputs_schema: {}, outputs_schema: {},
    skill_policy: { mode: 'cooperative', implicit: 'deny', ambient_allow: [], shadowed_skill_paths: [] }, requirements: { providers: provider ? [provider.id] : [], tools: [], mcp_servers: [], executables: [] }, finalization: { required: true, node_id: 'final' },
    nodes: [{ id: 'start', type: 'start', name: translate('开始', 'Start') }, role, final, { id: 'end', type: 'end', name: translate('结束', 'End') }], edges: [{ id: 'start-role', source: 'start', target: 'role' }, { id: 'role-final', source: 'role', target: 'final' }, { id: 'final-end', source: 'final', target: 'end' }] };
}
function App() {
  const t = useLocale();
  const [configuration, setConfiguration] = useState<Json | null>(null); const [library,setLibrary] = useState<Json[]>([]); const [roles,setRoles] = useState<Json[]>([]); const [runs,setRuns] = useState<Json[]>([]); const [capability,setCapability] = useState<Json | null>(null);
  const [pack,setPack] = useState<Json | null>(null); const [workflow,setWorkflow] = useState<Json | null>(null); const [dirty,setDirty] = useState(false); const [validation,setValidation] = useState<Json | null>(null);
  const [page,setPage] = useState('library'); const [tab,setTab] = useState('canvas'); const [selection,setSelection] = useState({ kind: 'workflow', id: '' }); const [runId,setRunId] = useState('');
  const [error,setError] = useState<Json | null>(null); const [busy,setBusy] = useState(0); const [invalid,setInvalid] = useState<Set<string>>(new Set());
  const [workspace,setWorkspace] = useState(''); const [runWorkspace,setRunWorkspace] = useState(''); const [inputs,setInputs] = useState<Json>({});
  const [strict,setStrict] = useState<Json | null>(null); const [filter,setFilter] = useState('');
  const [appView,setAppViewState] = useState(getAppView);
  const invalidChanged = useCallback((id: string, failed: boolean) => setInvalid(current => { if (current.has(id) === failed) return current; const next = new Set(current); if (failed) next.add(id); else next.delete(id); return next; }), []);
  const act = useCallback((work: () => Promise<any>) => { setBusy(n => n + 1); setError(null); void work().catch(cause => setError({ message: cause.message, ...(cause.detail ?? {}) })).finally(() => setBusy(n => n - 1)); }, []);
  async function refreshLibrary() {
    const [library, roles] = await Promise.all([api('list', { include_legacy: true }), api('role_templates')]);
    setLibrary(library); setRoles(roles);
  }
  async function reload() {
    const config = await request('/api/config'); setConfiguration(config); setStrict(config.config.strict_executor ?? null);
    if (config.config.version === 7) { const values = await Promise.all([api('list', { include_legacy: true }), api('role_templates')]); setLibrary(values[0]); setRoles(values[1]); }
  }
  useEffect(() => subscribeAppView(setAppViewState), []);
  useEffect(() => {
    if (isMcpAppContext && appView === 'settings') {
      act(async () => {
        const settingsRoot = document.getElementById('settings-shell');
        const template = document.getElementById('settings-template') as HTMLTemplateElement | null;
        if (!settingsRoot || !template) throw new Error('The embedded Provider settings view is missing its template.');
        if (settingsRoot.dataset.mounted !== 'true') {
          settingsRoot.replaceChildren(template.content.cloneNode(true));
          settingsRoot.dataset.mounted = 'true';
        }
        const settings = await import('../web/app.js');
        settings.mountSettings(settingsRoot);
      });
      return;
    }
    if (isMcpAppContext && appView !== 'workflows') return;
    act(async () => {
      await reload();
      if (!isMcpAppResource) return;
      const route = getInitialAppRoute();
      if (route.workflowId) {
        await saved(await api('read', { workflow_id: route.workflowId }));
        setSelection({ kind: 'workflow', id: '' }); setTab('canvas'); setPage('editor');
      } else if (route.runId) {
        setRunId(route.runId); setPage('run');
      }
    });
  }, [appView]);
  useEffect(() => { setRunWorkspace(''); setInputs({}); }, [workflow?.id]);
  useEffect(() => { const handler = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); }; window.addEventListener('beforeunload', handler); return () => window.removeEventListener('beforeunload', handler); }, [dirty]);
  async function mayLeave() { return !dirty || await confirmWorkbench(t('当前有未保存的草稿修改。放弃这些修改？', 'You have unsaved draft changes. Discard them?')); }
  function change(next: Json) { setWorkflow({ ...next, status: 'draft' }); setDirty(true); setValidation(null); }
  async function saved(value: Json) { setPack(value); setWorkflow(value.workflow); setDirty(false); setValidation(await api('validate', { workflow: value.workflow })); await refreshLibrary(); }
  async function save() { if (invalid.size) throw new Error(t('请先修正 JSON 格式错误。', 'Fix the invalid JSON first.')); if (!workflow) throw new Error(t('没有选中的 Workflow', 'No workflow is selected')); const value = await api(pack ? 'save' : 'create', { ...(pack ? { workflow_id: workflow.id, expected_revision: pack.revision_hash } : {}), workflow: { ...workflow, status: 'draft' } }); await saved(value); return value; }
  const providers = configuration?.config.providers ?? [];
  const graphIssues = workflow ? canvasIssues(workflow) : [];
  const matches = (item: Json) => `${item.name} ${item.id} ${item.description} ${item.model ?? ''}`.toLowerCase().includes(filter.toLowerCase());
  const visibleRoles = roles.filter(role => role.builtin && matches(role));
  const visibleWorkflows = library.filter(item => item.template_kind === 'workflow' && !item.legacy_task_type && matches(item));
  const legacyTaskDrafts = library.filter(item => item.legacy_task_type && matches(item));
  const customRoleDrafts = library.filter(item => item.template_kind === 'role' && !item.role_builtin_id && item.status !== 'ready' && matches(item));
  const customReadyRoles = library.filter(item => item.template_kind === 'role' && !item.role_builtin_id && item.status === 'ready' && matches(item));
  const workflowCard = (item: Json) => <div className="workflow-card-shell" key={item.id}><button className="workflow-card" onClick={() => openPack(item.id)}><div className="card-meta"><span>{item.system_managed?t('内置 Workflow','Built-in Workflow'):item.template_kind === 'role' ? 'Role' : 'Workflow'}</span><span>{item.import_mode === 'coarse' ? t('Skill 导入快照 · 未转换', 'Skill import snapshot · not converted') : item.enabled ? t('已启用', 'Enabled') : t('已禁用', 'Disabled')}</span><span>{({ cooperative: t('协作', 'Cooperative'), strict: t('严格', 'Strict') } as Record<string,string>)[String(item.skill_policy.mode)] ?? item.skill_policy.mode}</span></div><h2>{item.name}</h2><p>{item.description || t('尚未添加说明', 'No description yet')}</p><div className="card-footer"><span>{item.enabled ? t('已启用', 'Enabled') : t('已禁用', 'Disabled')}</span><span>{item.import_mode === 'coarse' ? t('仅为四节点导入骨架；请到「导入审查」完成转换', 'Four-node import scaffold; finish conversion in Import review') : item.validation.errors.length === 0 && item.validation.blockers.filter((issue:Json) => issue.code !== 'WORKFLOW_DRAFT').length === 0 ? item.status === 'ready' ? item.template_kind === 'role' ? t('已发布 · 可分配角色', 'Published · assignable role') : t('已发布 · 可新建任务', 'Published · ready for new tasks') : t('草稿 · 待发布', 'Draft · not published') : `${item.validation.errors.length} ${t('个结构问题', 'structural issue(s)')} · ${item.validation.blockers.filter((issue:Json) => issue.code !== 'WORKFLOW_DRAFT').length} ${t('个待处理事项', 'pending item(s)')}`}</span></div></button>{!item.system_managed&&<button className="workflow-card-delete danger" aria-label={t(`删除 ${item.name}`,`Delete ${item.name}`)} title={t('移入可恢复存储','Move to recoverable storage')} onClick={async event=>{event.stopPropagation();if(await confirmWorkbench(t(`删除「${item.name}」？它会移入可恢复存储，已有 Run 不受影响。`,`Delete “${item.name}”? It will move to recoverable storage; existing runs are unaffected.`)))act(async()=>{await api('delete',{workflow_id:item.id,expected_revision:item.revision_hash});if(pack?.workflow.id===item.id){setPack(null);setWorkflow(null);setDirty(false);}await refreshLibrary();});}}>{t('删除','Delete')}</button>}</div>;
  const openRun = (run: Json) => { if (run.conversation_requested) return; setRunId(rememberRun(run)); setPage('run'); };
  const openPack = async (id: string) => { if (await mayLeave()) act(async () => { await saved(await api('read', { workflow_id: id })); setSelection({ kind: 'workflow', id: '' }); setTab('canvas'); setPage('editor'); }); };
  return <InvalidContext.Provider value={invalidChanged}><FormValidContext.Provider value={!invalid.size}><div className="app-shell" aria-busy={busy > 0}>
    <header className="topbar"><a className="brand" href={isMcpAppContext ? '#workflows' : consoleHref('/workflows')} onClick={async e => { if (isMcpAppContext) { e.preventDefault(); if (appView === 'settings') setAppView('workflows'); else if (await mayLeave()) setPage('library'); } else { e.preventDefault(); if (await mayLeave()) setPage('library'); } }}><span className="brand-mark">C</span><strong>Codex</strong><span>Agents Workflow</span></a><nav aria-label={t('工作区导航', 'Workbench navigation')}><button className={page === 'library' ? 'active' : ''} onClick={async () => { if (await mayLeave()) setPage('library'); }}>{t('流程库', 'Workflow library')}</button><button className={page === 'runs' || page === 'run' ? 'active' : ''} onClick={async () => { if (await mayLeave()) { setPage('runs'); act(async () => setRuns(await api('runs'))); } }}>{t('运行记录', 'Run history')}</button><button className={page === 'settings' ? 'active' : ''} onClick={async () => { if (await mayLeave()) { setPage('settings'); act(async () => setCapability(await api('capabilities'))); } }}>{t('执行能力', 'Execution')}</button><a href={isMcpAppContext ? '#settings' : consoleHref('/')} onClick={async e => { if (isMcpAppResource) { e.preventDefault(); if (await mayLeave()) setAppView('settings'); } else if (dirty) { e.preventDefault(); const href = e.currentTarget.href; if (await mayLeave()) window.location.assign(href); } }}>{t('Provider 设置 ↗', 'Provider settings ↗')}</a></nav><span className="muted">{busy ? t('正在处理…', 'Working…') : configuration ? t('本地控制台', 'Local console') : t('连接中…', 'Connecting…')}</span><label className="language-switch"><span>{t('语言', 'Language')}</span><select aria-label={t('界面语言', 'Interface language')} value={getLocale()} onChange={event => setLocale(event.target.value)}><option value="zh-CN">中文</option><option value="en">English</option></select></label></header>
    <div id="workbench-content" className="workbench-content">
    {error && <div className="error-banner" role="alert"><div><strong>{error.code ?? t('操作失败', 'Operation failed')}{t('：', ': ')}{error.message}</strong><Details title={t('诊断详情', 'Diagnostics')} value={error}/></div><button aria-label={t('关闭错误', 'Close error')} onClick={() => setError(null)}>×</button></div>}
    {invalid.size > 0 && <div className="notice" role="alert">{t('存在无效 JSON，保存和启动已阻止。', 'Invalid JSON is blocking save and start.')}</div>}
    {configuration?.config.version === 6 ? <main className="landing"><span className="eyebrow">{t('准备迁移', 'Migration required')}</span><h1>{t('迁移到 Workflow 库', 'Migrate to the workflow library')}</h1><p>{t('迁移会保留固定 Provider、禁用状态、权限和审批要求，先创建备份，再一次性提交当前 Workflow 库。', 'Migration preserves fixed Providers, disabled states, permissions, and approval requirements. A backup is created before the current workflow library is submitted.')}</p><p>{t('当前配置：', 'Current configuration: ')}{configuration.storage?.config_path ?? t('本地用户配置', 'local user configuration')}</p><button className="primary" disabled={busy > 0} onClick={() => act(async () => { await api('migrate_v6'); await reload(); })}>{t('备份并迁移', 'Back up and migrate')}</button><Details title={t('当前配置修订', 'Current configuration revision')} value={{ revision: configuration.revision }}/></main> : <>
    {page === 'library' && <main className="library-page scroll"><div className="page-heading"><div><span className="eyebrow">{t('流程库', 'Workflow library')}</span><h1>{t('让流程可以审查，也可以执行。', 'Make workflows reviewable and executable.')}</h1><p>{t('从明确的步骤开始。每次运行固定完整版本，每个关键动作留下证据。', 'Start with explicit steps. Every run pins a complete version and records evidence for each important action.')}</p></div><div className="actions"><button onClick={() => act(refreshLibrary)}>{t('刷新', 'Refresh')}</button><button onClick={async () => { if (await mayLeave()) setPage('import'); }}>{t('从 Skill 导入', 'Import from Skill')}</button><button onClick={async () => { if (await mayLeave()) setPage('install'); }}>{t('安装 Workflow', 'Install Workflow')}</button><button onClick={async () => { if (await mayLeave()) { setPack(null); setWorkflow(roleDraft(providers)); setDirty(true); setSelection({ kind: 'workflow', id: '' }); setPage('editor'); setTab('canvas'); } }}>＋ {t('新建 Role', 'New role')}</button><button className="primary" onClick={async () => { if (await mayLeave()) { setPack(null); setWorkflow(draft()); setDirty(true); setSelection({ kind: 'workflow', id: '' }); setPage('editor'); setTab('canvas'); } }}>＋ {t('新建 Workflow', 'New workflow')}</button></div></div>
      <CacheCleanup act={act} busy={busy}/>
      <p className="muted">{t('Role 告诉 Main 在普通任务中何时、怎样自动调用一个帮手，不启动 Run；Workflow 是有具体目标的多步骤任务图，节点不会再次注入 Role。', 'A Role tells Main when and how to call one helper automatically during ordinary work without starting a Run. A Workflow is a purpose-built multi-step graph, and its nodes do not receive another Role prompt.')}</p>
      <Field label={t('搜索 Role 或 Workflow', 'Search roles or workflows')} value={filter} onChange={setFilter} placeholder={t('名称、说明、模型或 ID', 'Name, description, model, or ID')}/>
      <h2>{t('Role · 单 Agent 模式', 'Roles · single-agent profiles')}</h2>
      <div className="library-grid">{visibleRoles.map(role => { const executor=role.model??role.provider_id; const effort=role.reasoning_effort; const access=role.access === 'bounded_write' ? t('受限写入', 'Bounded write') : t('只读', 'Read only'); return <button className={'workflow-card'+(role.enabled?'':' is-disabled')} key={role.id} onClick={() => act(async () => { await saved(await api('customize_role',{workflow_id:role.id})); setSelection({kind:'workflow',id:''}); setTab('canvas'); setPage('editor'); })}><div className="card-meta"><span>{role.customized?t('内置 Role · 已自定义','Built-in role · customized'):t('内置 Role', 'Built-in role')}</span><span>{role.customization?.status==='draft'?t('自定义草稿','Customization draft'):`${role.enabled?t('已启用','Enabled'):t('未启用','Disabled')} · ${access}`}</span></div><h2>{role.name}</h2><p>{role.description}</p><div className="card-footer"><span>{executor}{effort?` · ${effort}`:''}{role.provider_enabled===false?` · ${t('Provider 未启用','Provider disabled')}`:''}</span><span>{t('点击编辑', 'Edit')}</span></div></button>; })}{customReadyRoles.map(workflowCard)}{customRoleDrafts.map(workflowCard)}</div>
      <h2>{t('Workflow · 具体任务流程', 'Workflows · purpose-built task processes')}</h2>
      <div className="library-grid">{visibleWorkflows.map(workflowCard)}</div>
      {legacyTaskDrafts.length > 0 && <details><summary>{t('旧版任务类型迁移草稿', 'Legacy migrated task drafts')} · {legacyTaskDrafts.length}</summary><p className="muted">{t('保留原始图和用户定制供检查；这些草稿不是新的 Role，也不会自动启动。', 'Original graphs and user customizations remain inspectable; these drafts are not new Roles and do not start automatically.')}</p><div className="library-grid">{legacyTaskDrafts.map(workflowCard)}</div></details>}
    </main>}
    {page === 'editor' && workflow && <div className="editor"><div className="editor-toolbar"><div><strong>{workflow.name}</strong><span className="muted"> · {workflow.template_kind==='role'?'Role':'Workflow'}{dirty ? t(' · 未保存', ' · Unsaved') : ` · r${workflow.revision} · ${workflow.status === 'ready' ? t('已发布', 'Published') : t('草稿', 'Draft')}`}</span></div><div className="actions"><button disabled={!!invalid.size || busy > 0} onClick={() => act(async () => setValidation(await api('validate', { workflow })))}>{t('校验', 'Validate')}</button><button disabled={!!invalid.size || busy > 0} onClick={() => act(save)}>{t('保存草稿', 'Save draft')}</button><button disabled={!!invalid.size || busy > 0 || (!dirty && pack?.workflow.status === 'ready')} onClick={() => act(() => publishEditedWorkflow({pack,dirty,save,request:api,onSaved:saved}))}>{workflow.template_kind==='role'?t('发布 Role', 'Publish role'):t('发布工作流', 'Publish workflow')}</button><button className="primary" disabled={!!invalid.size || busy > 0 || !workflow.enabled || workflow.template_kind==='role'} onClick={() => setTab('start')}>{t('新建任务', 'New task')}</button></div></div>
      <div className="editor-tabs" role="tablist">{[['canvas',t('画布','Canvas')],['resources',t('资源','Resources')],['review',t('导入审查','Import review')],['history',t('版本','Versions')],['json',t('完整 IR','Full IR')],['start',t('运行设置','Run settings')]].map(([id,label]) => <button role="tab" aria-selected={tab === id} key={id} disabled={!pack && !['canvas','json','start'].includes(id)} onClick={() => { if (dirty && !['canvas','json','start'].includes(id)) { setError({ message: t('请先保存草稿，再操作其固定资源和版本。', 'Save the draft before working with its pinned resources and versions.') }); return; } setTab(id); }}>{label}</button>)}<span className="spacer"/>{pack && <><button title={t('完整编辑器快照；可能包含私有转换素材，用于审计和排障','Complete editor snapshot; may include private conversion material for auditing and diagnosis')} onClick={() => act(async () => download(workflow.id + '.workflow.json', await api('export', { workflow_id: workflow.id, revision_hash: pack.revision_hash })))}>{t('完整 Pack 快照', 'Full Pack snapshot')}</button><button title={t('带兼容性、依赖和完整性校验，用于跨电脑安装','Includes compatibility, dependency, and integrity checks for installation on another computer')} onClick={() => act(async () => download(workflow.id + '.workflow-package.json', await api('export_workflow_package', { workflow_id: workflow.id, revision_hash: pack.revision_hash, package_version: '1.0.0' })))}>{t('可安装包', 'Install package')}</button><button disabled={dirty} onClick={() => act(async () => saved(await api('duplicate', { workflow_id: workflow.id, revision_hash: pack.revision_hash, new_id: uid(workflow.id.slice(0,30)), name: workflow.name + t(' 副本', ' copy') })))}>{t('复制', 'Duplicate')}</button>{pack.provenance?.kind!=='bundled_authoring_workflow'&&<button className="danger" disabled={dirty} onClick={async () => { if (await confirmWorkbench(t('将此 Workflow 移入可恢复存储？历史 Run 不受影响。', 'Move this workflow to recoverable storage? Existing runs are unaffected.'))) act(async () => { await api('delete', { workflow_id: workflow.id, expected_revision: pack.revision_hash }); setPack(null); setWorkflow(null); setPage('library'); await refreshLibrary(); }); }}>{t('删除', 'Delete')}</button>}</>}</div>
      {validation && <div className={'validation-bar ' + (validation.valid ? '' : 'invalid')}><strong>{validation.valid ? t('✓ 结构有效', '✓ Structure valid') : t('× 结构无效', '× Structure invalid')}</strong><span>{validation.errors.length===0 && validation.blockers.filter((i:Json)=>i.code!=='WORKFLOW_DRAFT').length===0 ? t('定义检查通过；启动时检查执行环境', 'Definition checks passed; the execution environment is checked at start time') : t('请处理下列事项', 'Resolve the following items')}</span>{[
        {title:t('结构问题','Structural issues'),issues:validation.errors},
        {title:t('待确认事项','Items needing confirmation'),issues:validation.blockers.filter((i:Json)=>['AI_INFERENCE_UNREVIEWED'].includes(i.code))},
        {title:t('依赖与执行限制','Dependencies and execution limits'),issues:validation.blockers.filter((i:Json)=>!['AI_INFERENCE_UNREVIEWED','WORKFLOW_DRAFT'].includes(i.code))}
      ].filter(group=>group.issues.length).map(group=><details key={group.title}><summary>{group.issues.length} {t('项','')}{group.title}</summary>{group.issues.map((issue:Json,index:number)=><button key={index} onClick={()=>{setTab(issue.code==='AI_INFERENCE_UNREVIEWED' || issue.code==='IMPORT_UNRESOLVED'?'review':'canvas');setSelection({kind:issue.node_id || issue.item_kind==='nodes'?'node':issue.edge_id || issue.item_kind==='edges'?'edge':'workflow',id:issue.node_id ?? issue.edge_id ?? issue.item_id ?? ''});}}>{issue.code} · {issue.node_id ?? issue.edge_id ?? issue.item_id ?? ''} · {issue.message}</button>)}</details>)}</div>}
      {tab === 'canvas' && workflow.import_status?.mode==='coarse' && <div className="notice" role="status">{t('当前画布是 Skill 导入骨架，不是转换结果。请打开「导入审查」，完成生成、独立审阅及确认后，真实任务图才会替换这里的四个节点。','This canvas is the Skill import scaffold, not the converted workflow. Open Import review; the generated task graph replaces these four nodes only after generation, independent review, and acceptance.')}</div>}
      {tab === 'canvas' && graphIssues.length > 0 && <section className="detail-page" role="alert"><h2>{t('草稿无法绘制', 'Draft cannot be rendered')}</h2><Details title={t('画布结构诊断', 'Canvas structure diagnostics')} value={graphIssues}/><p>{t('原始 IR 已保留，修复后可继续编辑。', 'The original IR is preserved; fix it to continue editing.')}</p><button onClick={() => setTab('json')}>{t('打开完整 IR 修复', 'Open the full IR to repair it')}</button></section>}
      {tab === 'canvas' && !graphIssues.length && <EditorBoundary workflow={workflow} edit={() => setTab('json')}><div className="editor-body"><aside className="palette scroll"><h2>{t('节点', 'Nodes')}</h2><p>{t('拖入画布，或点击添加。', 'Drag onto the canvas or click to add.')}</p>{nodeKinds.map(kind => <button draggable key={kind} onDragStart={e => { e.dataTransfer.setData('application/sol-node',kind); e.dataTransfer.effectAllowed = 'move'; }} onClick={() => { const node = newNode(kind); change({ ...workflow, nodes: [...workflow.nodes,node] }); setSelection({ kind: 'node', id: node.id }); }}>{({agent:t('Agent','Agent'),condition:t('条件','Condition'),parallel:t('并行','Parallel'),join:t('汇合','Join'),skill_ref:t('Skill 引用','Skill ref'),subworkflow:t('子 Workflow','Subworkflow'),tool:t('工具','Tool'),human_gate:t('人工确认','Human gate'),start:t('开始','Start'),end:t('结束','End')} as Record<string,string>)[kind] ?? kind}<span>＋</span></button>)}<p>{t('从连接点拖动创建边。点击节点或连线编辑属性。', 'Drag from a connector to create an edge. Click a node or edge to edit its properties.')}</p></aside><Canvas workflow={workflow} providers={providers} onChange={change} onSelect={(kind,id) => setSelection({ kind,id })}/><Inspector key={selection.kind + selection.id} workflow={workflow} selection={selection} providers={providers} change={change} select={(kind,id) => setSelection({ kind,id })} inline={() => act(async () => { if (dirty || !pack) throw new Error(t('请先保存精确 SkillRef 版本。', 'Save the exact SkillRef version first.')); await saved(await api('inline_skill', { workflow_id: workflow.id, node_id: selection.id, expected_revision: pack.revision_hash })); })}/></div></EditorBoundary>}
      {['resources','history','review'].includes(tab) && pack && <PackPanels pack={pack} tab={tab} saved={saved} act={act} providers={providers} openRun={openRun} workspace={workspace} setWorkspace={setWorkspace}/>}
      {tab === 'json' && <section className="detail-page scroll"><h2>{t('完整 Workflow IR', 'Full workflow IR')}</h2><p>{t('未知领域字段会原样保留。此处可编辑可视属性表未覆盖的扩展字段；保存前由后端检查。', 'Unknown fields are preserved as-is. Edit extension fields not covered by the visual editor here; the backend checks them before saving.')}</p><JsonField label={t('工作流 JSON', 'Workflow JSON')} value={workflow} onChange={value => { if (!value || !Array.isArray(value.nodes) || !Array.isArray(value.edges) || !value.skill_policy || !value.finalization) throw new Error(t('IR 缺少节点、连接、Skill 策略或最终验收字段', 'IR is missing nodes, edges, Skill policy, or finalization fields')); change(value); }} rows={28}/></section>}
      {tab === 'start' && <section className="detail-page scroll"><h2>{t('运行一次任务', 'Run a task')}</h2><p>{t('这里仅运行已发布版本，不会保存或发布工作流。', 'This runs only the published version; it does not save or publish the workflow.')}</p>{(dirty || !pack || workflow.status !== 'ready') && <p role="status">{t('请先点击顶部「发布工作流」，再运行任务。发布无需填写任务描述。', 'Click “Publish workflow” above before running a task. Publishing does not require a task description.')}</p>}<p>{t('描述本次任务后即可启动。默认允许在任务工作目录内生成和修改文件，主 Agent 根据工作流处理具体步骤、参数和文件操作。', 'Describe this task to start it. By default, the task may create and modify files in its workspace; the Main Agent handles steps, parameters, and file operations from the workflow.')}</p><p>{t('填写本次任务目标，不是系统提示词。也可以让模型生成草稿，再补充必要信息。', 'Enter the goal for this task, not a system prompt. You can also have a model draft it and then add the missing details.')}</p><button disabled={busy>0} onClick={()=>act(async()=>{const result=await api('generate_task_brief',{...(pack?{workflow_id:pack.workflow.id,revision_hash:pack.revision_hash}:{}),workflow,existing:inputs.task ?? ''});setInputs({task:result.task});})}>{t('一键生成任务描述', 'Generate task description')}</button><p className="muted">{t('使用当前注册的任务描述生成配置；生成后可继续编辑。', 'Uses the registered task-description generator; you can edit the result.')}</p><Field label={t('这次要做什么', 'What should this task do?')} multiline value={inputs.task ?? ''} onChange={task=>setInputs({task})}/><details><summary>{t('工作目录（可选）', 'Workspace (optional)')}</summary><p>{t('留空时自动创建。处理已有项目时可选择它的目录。', 'Leave blank to create one automatically. Choose an existing project folder when working on an existing project.')}</p><Field label={t('项目文件夹', 'Project folder')} value={runWorkspace} onChange={setRunWorkspace}/></details><button className="primary" disabled={dirty || !pack || workflow.status !== 'ready' || !workflow.enabled || !!invalid.size || busy > 0} onClick={() => act(async () => openRun(await launchEditedWorkflow({pack,dirty,request:api,conversationLaunch:launchWorkflowInConversation,options:{launch_mode:'task',...(runWorkspace?{workspace:runWorkspace}:{}),inputs,main_actor:'human-console'}})))}>{busy>0?t('正在准备任务…','Preparing task…'):t('运行任务','Run task')}</button></section>}
    </div>}
    {page === 'import' && <SkillImportPanel act={act} busy={busy} providers={providers} imported={async value => { await saved(value); setPage('editor'); setTab('review'); }}/>}
    {page === 'install' && <WorkflowInstallPanel act={act} busy={busy} installed={async value => { await saved(value); setPage('editor'); setTab('review'); }} back={() => setPage('library')}/>}
    {page === 'settings' && <main className="detail-page scroll"><h1>{t('执行能力', 'Execution')}</h1><LocalClients/><RuntimeDependencies/><p>{t('Strict 约束已验证的目录、显式 Skill 输入与工具代理。具体系统及二进制必须通过资格检查。', 'Strict execution uses verified directories, explicit Skill inputs, and tool proxies. The target system and binaries must pass qualification checks.')}</p><Details title={t('当前资格、限制和诊断', 'Current qualification, limits, and diagnostics')} value={capability}/>{strict && <><label className="check"><input type="checkbox" checked={strict.enabled} onChange={e => setStrict({ ...strict, enabled: e.target.checked })}/>{t('启用已验证的 Strict 执行器', 'Enable the verified Strict executor')}</label><Field label={t('Codex 可执行文件绝对路径', 'Absolute Codex executable path')} value={strict.codex_binary} onChange={codex_binary => setStrict({ ...strict, codex_binary })}/><Field label={t('已验证二进制 SHA-256', 'Verified binary SHA-256')} value={strict.binary_sha256} onChange={binary_sha256 => setStrict({ ...strict, binary_sha256 })}/><p>{t('host_chatgpt 复用当前 Codex 登录，无需逐节点登录；managed_chatgpt 使用独立的手动登录。', 'host_chatgpt reuses the current Codex login; managed_chatgpt uses a separate manual login.')}</p><Select label={t('认证模式', 'Authentication mode')} value={strict.authentication.mode} options={[{value:'host_chatgpt',label:'host_chatgpt'},{value:'managed_chatgpt',label:'managed_chatgpt'},{value:'environment_api_key',label:'environment_api_key'}]} onChange={mode => setStrict({ ...strict, authentication: { ...strict.authentication, mode } })}/>{strict.authentication.mode === 'environment_api_key' && <Field label={t('API Key 环境变量名（只填名称）', 'API key environment variable name (name only)')} value={strict.authentication.api_key_env} onChange={api_key_env => setStrict({ ...strict, authentication: { ...strict.authentication, api_key_env } })}/>}<p>{t('主 Agent 沿用启动任务的聊天当前模型和思考强度。独立从工作台启动时沿用 Codex 设置，无需在 Workflow 中指定。', 'Main follows the calling chat’s current model and reasoning selection. Standalone Workbench launches follow Codex settings; no Main model is specified in the Workflow.')}</p><button disabled={busy > 0} onClick={() => act(async () => { await request('/api/config', { config: { ...configuration?.config, strict_executor: strict }, expected_revision: configuration?.revision }, 'PUT'); await reload(); })}>{t('保存明确的执行器设置', 'Save explicit executor settings')}</button></>}</main>}
    {page === 'runs' && <main className="library-page scroll"><div className="page-heading"><div><span className="eyebrow">{t('运行记录', 'Run history')}</span><h1>{t('状态来自实际运行日志。', 'Status comes from the live run journal.')}</h1></div><div><button disabled={busy > 0} onClick={() => act(async () => { await api('cleanup_run_history'); setRuns(await api('runs')); })}>{t('清理已结束记录', 'Clear finished history')}</button><button onClick={() => act(async () => setRuns(await api('runs')))}>{t('刷新', 'Refresh')}</button></div></div><p>{t('启动时自动清理超过 24 小时的已完成和失败记录；手动清理会立即清除这些记录。运行中、暂停和中断任务及工作文件会保留。', 'Launch automatically clears completed and failed records older than 24 hours. Manual cleanup clears them immediately. Active, paused and interrupted tasks and working files are retained.')}</p>{runs.map(run => <button className="run-row" key={run.run_id} onClick={() => { setRunId(run.run_id); setPage('run'); }}><strong>{run.workflow_id ?? run.run_id}</strong><Status value={run.status}/><code>{run.run_id}</code><span>{run.updated_at}</span></button>)}{!runs.length && <p>{t('还没有运行记录。', 'No runs yet.')}</p>}</main>}
    {page === 'run' && <RunPanel key={runId} runId={runId} providers={providers} act={act} onRun={id => setRunId(id)}/>}
    </>}
    </div>
  </div></FormValidContext.Provider></InvalidContext.Provider>;
}
initializeAppView();
createRoot(document.getElementById('root')!).render(<App/>);
